export type Submission = {
  id: string;
  name: string | null;
  email: string | null;
  created_at: string | null;
  course: string | null;
  first_name: string | null;
  last_name: string | null;
  nickname: string | null;
  phone: string | null;
  payment_method: string | null;
  birth_date: string | null;
  occupation: string | null;
  business_description: string | null;
  wants_invoice: boolean | null;
  invoice_type: string | null;
  personal_tax_name: string | null;
  personal_tax_id: string | null;
  personal_address: string | null;
  personal_invoice_email: string | null;
  company_name: string | null;
  company_tax_id: string | null;
  company_address: string | null;
  company_invoice_email: string | null;
  company_contact_name: string | null;
  company_contact_phone: string | null;
  accepted_terms: boolean | null;
  signature_url: string | null;
  is_hidden_in_admin: boolean | null;
  outbound_called: boolean | null;
  outbound_call_note: string | null;
  disqualified: boolean | null;
  no_need_follow_up: boolean | null;
};
